### PR TITLE
Issue #17: Improve tag matching logic in LexerUtility to avoid misidentifying valid tag

### LINKED ISSUE #17: `LexerUtility.getUnclosedTagNameTokens`  incorrectly identifies tags as unmatched
Example:

```
 * <p>Example</p>
 * <p>Item with paragraph
```

Output:

> line 1:4 no viable alternative at input '</'

Tree:
```
'- javadoc
   |- mainDescription
   |  |- htmlElement
   |  |  |- htmlTagStart
   |  |  |  |- TOKEN[type: TAG_OPEN, text: <]
   |  |  |  |- TOKEN[type: TAG_NAME, text: p]
   |  |  |  '- TOKEN[type: TAG_CLOSE, text: >]
   |  |  '- nonTightHtmlContent
   |  |     '- TOKEN[type: TEXT, text: Example]
   |  |- [174 58]
   |  |  '- [174 58]
   |  |- htmlElement
   |  |  |- TOKEN[type: TAG_OPEN, text: <]
   |  |  |- TOKEN[type: TAG_SLASH, text: /]
   |  |  |- TOKEN[type: TAG_NAME, text: p]
   |  |  '- TOKEN[type: TAG_CLOSE, text: >]
   |  |- TOKEN[type: NEWLINE, text: \n]
   |  '- htmlElement
   |     |- htmlTagStart
   |     |  |- TOKEN[type: TAG_OPEN, text: <]
   |     |  |- TOKEN[type: TAG_NAME, text: p]
   |     |  '- TOKEN[type: TAG_CLOSE, text: >]
   |     '- nonTightHtmlContent
   |        '- TOKEN[type: TEXT, text: Item with paragraph]
```

---

The utility method detects the first p tag in 1:4 as unmatched.

Image

Image

### PR DESCRIPTION
**Pull request by mahfouz72**
closes #17

### CODE REVIEW

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Items:

File: src/main/java/LexerUtility.java [hunk 1]
```diff
@@ -6,41 +6,51 @@
 
 public final class LexerUtility {
 
+    private static final Set<String> VOID_TAGS = Set.of(
```
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/LexerUtility.java]: done

File: src/main/java/LexerUtility.java [hunk 2]
```diff
@@ -10,37 +10,40 @@ private LexerUtility() {
...
+    public static void matchClosingTag(Deque<Token> openTagNameTokens,
+                                       Token closeTagNameToken, List<Token> unclosedTags) {
+        boolean matched = false;
+
+        while (!openTagNameTokens.isEmpty()) {
+            Token openTagNameToken = openTagNameTokens.pop();
+            String openTagName = openTagNameToken.getText();
+            String closeTagName = closeTagNameToken.getText();
+
+            if (openTagName.equals(closeTagName)) {
```
[the remark this answers is not in the document]
Comment (mahfouz72) [reply src/main/java/LexerUtility.java]: done

File: src/main/resources/JavadocLexer.g4 [hunk 3]
```diff
@@ -73,13 +74,12 @@ import org.antlr.v4.runtime.Token;
     @Override
     public void emit(Token token) {
         super.emit(token);
-        if (token.getType() == TAG_NAME) {
+        if (token.getType() == TAG_NAME && !LexerUtility.isSelfClosing(_input)) {
```
Comment (nrmancuso) [inline src/main/resources/JavadocLexer.g4:77]: It is not clear to me why we want to iterate through every tag we have for every single token that we lex, regardless of type. The lexer is the most performance sensitive part of our project; we should avoid any extra work whenever possible. This is why I chose to just dump everything into the collections indiscriminately, then lazily build the collection of unclosed tags only when we need it.

**Review by nrmancuso — CHANGES_REQUESTED** [review]
With everything that is changed here, it is not apparent what the actual bug was. @mahfouz72 please point to what caused the bug and let's focus our efforts on that only.

File: src/main/resources/JavadocLexer.g4 (hunk 3 above)
Comment (rnveach) [inline src/main/resources/JavadocLexer.g4:77]: Probably a stupid question, but why don't we just move all this Java code to the LexerUtility since we have it already?

**Comment by mahfouz72** [comment]
> it is not apparent what the actual bug was


@nrmancuso 

```
 * <p>Example</p>
 * <p>Item with paragraph
```

The opening tag stack would be:

1. `<p>` from line 2 <------ top of the stack
2. `<p>` from line 1 

When encountering the closing tag `</p>` from line 1, the current implementation incorrectly compares it with the most recent opening tag (the 'p' from line 2) rather than matching it with its corresponding opening tag (the p from line 1).

When encountering a closing tag, we should only try to match the tags that were opened before the current closing tag. 

That's why I thought of this approach, when we encounter a closing tag, we immediately try to match it with the most recent valid opening tag

File: src/main/resources/JavadocLexer.g4 (hunk 3 above)
Comment (rnveach) [reply src/main/resources/JavadocLexer.g4:77]: > for every token we lex
> the overridden emit method

I think your focusing on the new changes, my question was more on any java code in the lexer. Another example would be `isJavadocTag`.

Comment (nrmancuso) [reply src/main/resources/JavadocLexer.g4:77]: Let's add this entire condition to the utility

**Review by nrmancuso — CHANGES_REQUESTED** [review]
Last items:

File: src/main/java/LexerUtility.java [hunk 4]
```diff
@@ -20,7 +20,8 @@ public static Set<SimpleToken> getUnclosedTagNameTokens(
             boolean matched = false;
             while (!unmatchedOpen.isEmpty()) {
                 Token openingTag = unmatchedOpen.pop();
-                if (openingTag.getText().equalsIgnoreCase(closingTag.getText())) {
+                if (openingTag.getText().equalsIgnoreCase(closingTag.getText())
+                        && openingTag.getLine() <= closingTag.getLine()) {
```
Comment (nrmancuso) [inline src/main/java/LexerUtility.java:24]: What if both closing tags are on the same line?

**Review by nrmancuso — APPROVED** [review]

**Review by rnveach — APPROVED** [review]
